'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { ArrowUpRight, Clock, ShoppingBag, IndianRupee, Users, type LucideIcon } from 'lucide-react';
import { apiFetch } from '@/lib/client-api';

type Order={id:string;orderNumber?:string;customer?:string;customerName?:string;items?:any[];status:string;total:number};
type Summary={totalOrders:number;totalRevenue:number;completedOrders:number;pendingOrders:number;customers:number;averageOrder:number};

export default function Admin(){
 const [orders,setOrders]=useState<Order[]>([]); const [report,setReport]=useState<Summary|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 async function load(){try{const [o,r]=await Promise.all([apiFetch<{orders:Order[]}>('/api/orders'),apiFetch<{summary:Summary}>('/api/reports')]);setOrders(o.orders||[]);setReport(r.summary||null);setError('')}catch(e:any){setError(e.message||'Dashboard data could not be loaded')}finally{setLoading(false)}}
 useEffect(()=>{load();const timer=window.setInterval(()=>{if(document.visibilityState==='visible')load()},20000);return()=>window.clearInterval(timer)},[]);
 const revenue=Number(report?.totalRevenue||0), totalOrders=Number(report?.totalOrders||0), customers=Number(report?.customers||0), avg=totalOrders?revenue/totalOrders:0;
 const cards:Array<[string,string,LucideIcon]>=[['Revenue',`₹${revenue.toFixed(0)}`,IndianRupee],['Orders',String(totalOrders),ShoppingBag],['Customers',String(customers),Users],['Avg. order',`₹${avg.toFixed(0)}`,Clock]];
 return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-[#697552]">Overview</p><h1 className="serif mt-1 text-4xl font-semibold">Good evening.</h1><p className="mt-2 text-sm text-[#6b6258]">Restaurant performance at a glance.</p></div><Link href="/admin/orders" className="flex items-center gap-2 rounded-full bg-[#3F4A32] px-5 py-3 text-sm font-semibold text-white">Open orders<ArrowUpRight size={17}/></Link></div>{error&&<div className="mt-6 rounded-2xl border border-[#A85C43]/30 bg-[#A85C43]/10 p-4 text-sm text-[#8f4935]">{error}</div>}
 <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([title,value,Icon])=><div key={title} className="rounded-2xl border border-[#D9C7A8] bg-[#FBF7EF] p-5"><Icon size={18} className="text-[#697552]"/><p className="mt-5 text-sm text-[#6b6258]">{title}</p><p className="serif mt-1 text-3xl font-semibold">{loading?'—':value}</p></div>)}</div>
 <div className="mt-8 grid gap-6 lg:grid-cols-[1.5fr_1fr]"><section className="rounded-3xl border border-[#D9C7A8] bg-[#FBF7EF] p-6"><div className="flex items-center justify-between"><h2 className="serif text-2xl font-semibold">Live orders</h2><Link href="/admin/orders" className="text-sm underline">View all</Link></div><div className="mt-5 space-y-3">{orders.slice(0,5).map(order=><div key={order.id} className="flex items-center justify-between rounded-2xl bg-[#F5EEDF] p-4"><div><b>{order.orderNumber||order.id}</b><p className="text-sm text-[#6b6258]">{order.customer||order.customerName||'Walk-in customer'} · {order.items?.length||0} line items</p></div><div className="text-right"><span className="rounded-full bg-[#D9C7A8] px-3 py-1 text-xs font-semibold">{order.status}</span><p className="mt-2 text-sm font-semibold">₹{order.total}</p></div></div>)}{!loading&&!orders.length&&<p className="py-10 text-center text-sm text-[#6b6258]">No orders yet.</p>}</div></section><section className="rounded-3xl bg-[#3F4A32] p-6 text-[#F5EEDF]"><h2 className="serif text-2xl font-semibold">Quick actions</h2><div className="mt-5 grid gap-3"><Link href="/admin/menu" className="rounded-2xl bg-[#697552] p-4">Edit menu →</Link><Link href="/admin/tables" className="rounded-2xl bg-[#697552] p-4">Manage tables →</Link><Link href="/admin/inventory" className="rounded-2xl bg-[#697552] p-4">Manage inventory →</Link><Link href="/admin/customers" className="rounded-2xl bg-[#697552] p-4">View customers →</Link><Link href="/admin/kitchen" className="rounded-2xl bg-[#697552] p-4">Open KDS →</Link></div></section></div></div>;
}
